config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get 'home/about' => 'homes#about'
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]

  resources :books, only: [:create, :index, :show, :edit, :update]

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { in: 1..200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def create
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
    if @newbook.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@newbook.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @newbook = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    user = @book.user
    if user.id != current_user.id
     redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def create
    @home = Home.new(home_params)
    @home.home_id = current_user.id
      @home.save
      flash[:notice] = "Signed out successfully."
      redirect_to root
  end


  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    if @user.save
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      @users = User.all
      render :root
    end
  end

  def index
    @users = User.all
    @user = current_user
    @newbook = Book.new
  end

  def show
    @user = User.find(params[:id])
    @newbook = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>

  <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this obj from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

  <%= form_with model:@book do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit 'Update Book' %>
  </div>
  <%= link_to 'Show', book_path(@book.id) %>
  <%= link_to 'Back', books_path %>
  <% end %>
</div>

app/views/books/index.html.erb
<%= render 'users/userinfo', user: current_user, book: @newbook %>

<div class="col-md-8 offset-md-1">
  <h1>Books</h1>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
      <th>
        <%= link_to user_path(book.user_id) do %>
        <%= image_tag book.user.get_profile_image %>
        <% end %>
      </th>
      <th><%= link_to book.title, book_path(book.id) %></th>
      <th><%= book.body %></th>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<%= render 'users/userinfo', user: @user, book: @newbook %>

<div class="col-md-8 offset-md-1">
  <h1>Book detail</h1>
  <div class="table">
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
            <%= image_tag 'no_image.jpeg' %>
            <%= @book.user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to @book.title, book_path(@book.id) %>
        </td>
        <td>
          <%= @book.body %>
        </td>
        <% if @book.user == current_user %>
        <td>
          <%= link_to 'Edit', edit_book_path(@book.id),  class:"btn btn-success" %>
        </td>
        <td>
          <%= link_to 'Destroy',destroy_book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか?'}, class:"btn btn-danger" %>
        </td>
        <% end %>
      </tr>
    </tbody>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto">
      <h1>
        Welcom to
        <i class="fas fa-solid fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
 <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-am-10 col-ig-8 col-xl-6">
      <h1>
    Welcome to
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>!!
  </h1>
      <p>
    In
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>,
  </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers21</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet">
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id) do %>
            <i class="fas fa-home"></i>Home
            <% end %>
          </li>

          <li>
            <%= link_to users_path do %>
              <i class="fas fa-solid fa-users"></i>Users
            <% end %>
          </li>

          <li>
            <%= link_to books_path do %>
            <i class="fas fa-solid fa-book-open"></i>Books
            <% end %>
          </li>

          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i>Log out
            <% end %>
          </li>
          <% else %>
          <li>
            <%= link_to root_path do %>
            <i class="fas fa-home"></i>Home
            <% end %>
          </li>

          <li>
            <%= link_to home_about_path do %>
            <i class="fas fa-solid fa-link"></i>About
            <% end %>
          </li>

          <li>
            <%= link_to new_user_registration_path do %>
            <i class="fas fa-solid fa-user-plus"></i>Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
            <i class="fas fa-sign-in-alt"></i>Log in
            <% end %>
          </li>
          <% end %>
        </ul>
        </div>
      </div>
    </nav>
  </header>

  <% if flash[:notice] %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end %>

    <%= yield %>
　<footer>
　  <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
　</footer>

  </body>
</html>

app/views/users/_userinfo.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <h1>User info</h1>
      <%= image_tag user.get_profile_image %>
      <table class="table">
        <tbody>
          <tr>
          <th>name</th>
          <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
          <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <div class="mt-3">
        <h1>New book</h1>

        <% if book.errors.any? %>
          <%= book.errors.count %>件のエラーが発生しました
          <ul>
            <% book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

      </div>
      <%= form_with model:book, local:true do |f| %>
      <div class="form-group">
      <label for="book_title"><p>Title</p></label>
      <%= f.text_field :title %>
      </div>
      <div class="form-group">
      <label for="book_opinion"><p>Opinion</p></label>
      <%= f.text_area :body %>
      <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>User info</h1>

    <% if @user.errors.any? %>
      <%= @user.errors.count %>件のエラーが発生しました
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>


    <%= form_with model:@user do |f| %>
    <div class="form-group">
      <label for="user_name">Name</label>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <label for="user_image">Image</label>
      <%= f.file_field :profile_image, accept: "image/*" %>
    </div>
    <div class="form-group">
      <label for="user_introduction">Introduction</label>
      <%= f.text_area :introduction %>
    </div>
    <div class="form-group">
      <%= f.submit 'Update User' %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users/userinfo', user: @user, book: @newbook %>

<div class="col-md-8 offset-md-1">
  <h1>Users</h1>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
      <td>
        <%= image_tag user.get_profile_image %>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td>
        <%= link_to 'Show', user_path(user.id) %>
      </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'userinfo', user: @user, book: @newbook %>

<div class="col-md-8 offset-md-1">
  <h1>Books</h1>
  <table class="table tabel-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th><p>Title</p></th>
        <th><p>Opinion</p></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <th>
          <%= link_to user_path(book.user_id) do %>
          <%= image_tag book.user.get_profile_image %>
          <% end %>
        </th>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>